# Generated by Django 4.2.3 on 2023-07-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
